#!/bin/bash

device=$(bluetoothctl devices | head -1 | cut -f2 -d' ')
connected=$(bluetoothctl info "$device" | grep "Connected: yes")
if [[ -n "$connected" ]]; then
  bluetoothctl disconnect "$device"
else
  bluetoothctl connect "$device"
fi
