#!/bin/bash

pkill -9 dunst
pkill -9 nm-applet
pkill -9 blueman-applet

swww kill

pkill -9 hypridle

# pkill -9 wl-paste
pkill -f -9 polkit-gnome-authentication-agent-1

sh ~/.config/waybar/waybar.sh kill
sh ~/dotfiles/scripts/bluetooth-options/toggle-power
