#!/bin/bash

# Initialize Wallpaper Engine
sh ~/dotfiles/scripts/init-wallpaper-engine

# Start Bar
sh ~/.config/waybar/waybar.sh

# Load cliphist history
wl-paste --watch cliphist store &

# Load network manager applet
nm-applet --indicator &

# Bluetooth applet
blueman-applet &

# Start idle
hypridle &
