#!/bin/bash

# Load Preferred Visual Config
echo 'source = ~/.config/hypr/conf/windows/preferred.conf' >~/.config/hypr/conf/window.conf
echo 'source = ~/.config/hypr/conf/decorations/preferred.conf' >~/.config/hypr/conf/decoration.conf
echo 'source = ~/.config/hypr/conf/animations/preferred.conf' >~/.config/hypr/conf/animation.conf
echo 'source = ~/.config/hypr/hyprfocus.conf' >~/.config/hypr/plugins.conf
hyprctl reload

# Initialize Wallpaper Engine
sh ~/dotfiles/scripts/init-wallpaper-engine

# Start Bar
sh ~/.config/waybar/waybar.sh

# Load cliphist history
wl-paste --watch cliphist store &

# Load network manager applet
nm-applet --indicator &

# Bluetooth applet
blueman-applet &

# Start idle
hypridle &

hyprpm reload &

# Environment for xdg-desktop-portal-hyprland
sh ~/.config/hypr/scripts/xdg.sh
