#!/bin/bash

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
. "$HOME/.local/share/cargo/env"

eval "$(oh-my-posh init bash --config ~/.config/posh/config.toml)"
eval "$(fzf --bash)"
eval "$(zoxide init bash)"
