#!/bin/bash

dir="$HOME/pictures/screenshots"
name="window_$(date +%d-%m-%Y_%H:%M:%S).png"

info=$(hyprctl activewindow)
at=$(echo "$info" | grep 'at:' | awk '{print $2}')
size=$(echo "$info" | grep 'size:' | awk '{print $2}' | tr ',' 'x')

grim -g "$at $size" "$dir/$name"
[ ! -f "$dir/$name" ] && exit
notify-send 'Current Window Screenshot' "Saved as $name"

wl-copy < "$dir/$name"
swappy -f "$dir/$name"
