#!/bin/bash
mode1="Performance\0icon\x1fpower-profile-performance-symbolic"
mode2="Riced\0icon\x1fhyprland"

case "$1" in
performance) sh ~/dotfiles/scripts/modes/performance ;;
riced) sh ~/dotfiles/scripts/modes/riced ;;
choose)
  mode=$(dmenu " Mode: " "$mode1\n$mode2")
  mode=${mode,,}
  sh "$0" "$mode"
  ;;
esac
