#!/bin/bash

source='alsa_input.pci-0000_00_1f.3.analog-stereo'
file="area_$(date +%d-%m-%Y_%H-%M-%S).mp4"


wf-recorder -a=$source -y -f $file
# mic: alsa_input-mono-sterio
# audio: bluez_output.monior
