#!/bin/bash
# __        __    _ _
# \ \      / /_ _| | |_ __   __ _ _ __   ___ _ __
#  \ \ /\ / / _` | | | '_ \ / _` | '_ \ / _ \ '__|
#   \ V  V / (_| | | | |_) | (_| | |_) |  __/ |
#    \_/\_/ \__,_|_|_| .__/ \__,_| .__/ \___|_|
#                    |_|         |_|
# -----------------------------------------------------
echo "// Setting wallpaper"

# Cache file for holding the current wallpaper
cache_file="$HOME/.cache/current_wallpaper"
echo "Cache file: $cache_file"

blurred="$HOME/.cache/blurred_wallpaper.png"
echo "Blurred file: $blurred"

blur="50x30"

# Create cache file if not exists
if [ ! -f "$cache_file" ]; then
  echo "$HOME/pictures/wallpapers/default.avif" >"$cache_file"
  echo "Cache file did not existed, creating"
fi

current_wallpaper=$(cat "$cache_file")
echo "Current wallpaper: $current_wallpaper"

wallpaper="$1"

case "$wallpaper" in
# Load wallpaper from .cache of last session
"init")
  echo "// Using current wallpaper"

  if [ -f "$cache_file" ]; then
    wallpaper="$current_wallpaper"
  else
    wallpaper=$(find ~/pictures/wallpapers/ | shuf -n 1)
  fi
  ;;

# Randomly select wallpaper
*)
  if [ -z "$wallpaper" ]; then
    echo "// Random wallpaper"
    wallpaper=$current_wallpaper

    while [[ $wallpaper == "$current_wallpaper" ]]; do
      wallpaper=$(find ~/pictures/wallpapers/ | shuf -n 1)
    done
  fi
  ;;
esac

if [ "$wallpaper" == "$current_wallpaper" ]; then
  exit
fi

# Write selected wallpaper into .cache files
echo "$wallpaper" >"$cache_file"

# Load current color scheme
echo "// Setting colorscheme using: $wallpaper"
pkill -9 dunst
wallust run "$wallpaper"

# Get wallpaper image name
wallname="${wallpaper##*/}"
wallname="${wallname%%.*}"

echo "// Setting wallpaper $wallpaper"

# Set the workspaces wallpaper
swww img "$wallpaper"
# swww img -n workspaces "$wallpaper" \
  #--transition-type=weba \
  #--transition-bezier .43,1.19,1,.4 \
  #--transition-fps=60 \
  #--invert-y
  #--transition-duration=2 \
#--transition-pos "$(hyprctl cursorpos | tr -d ' ')"

# Create blurred wallpaper
is_gif=$(file "$wallpaper" | grep GIF)

if [ "$is_gif" ]; then
  magick "$wallpaper" "PNG32:$blurred"
  mv ~/.cache/blurred_wallpaper-0.png "$blurred"
  rm ~/.cache/blurred_wallpaper-*
  magick "$blurred" -resize 75% -quality 50% "$blurred"
else
  magick "$wallpaper" -resize 75% -quality 50% "$blurred"
fi

magick "$blurred" -blur "$blur" "$blurred"

# Set the overview wallpaper
# swww img -n overview "$blurred"
