#!/bin/bash

case "$1" in
s) sh ~/dotfiles/scripts/ytfzf-options/subs "${@:2}" ;;
d) sh ~/dotfiles/scripts/ytfzf-options/download "${@:2}" ;;
*) sh ~/dotfiles/scripts/ytfzf-options/search "$@" ;;
esac
