[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"

[window]
opacity = 0.76
#decorations = "Transparent"
padding = { x = 5, y = 5 }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

[[hints.enabled]]
binding = { key = "H", mods = "Alt" }
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

# [hints]
# enabled=[
#   { binding = { key = "H", mods = "Alt" }, command = "xdg-open", hyperlinks = true, post_processing = true, persist = false, mouse.enabled = true, regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+" },
# { binding = { key = "O", mods = "Alt" }, command = "copyout", hyperlinks = true, post_processing = false, persist = false, mouse.enabled = true, regex = ".*" },
# ]

[general]
import = [
  "~/.cache/wal/alacritty.toml",
  "~/.config/alacritty/keybindings.toml"
]
