[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"

[window]
opacity = 0.75

[window.padding]
x = 10
y = 10

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block" }
