final_space = true
enable_cursor_positioning = true
version = 3

[secondary_prompt]
background = "transparent"
foreground = "#ffffff"
template = "-> "

[[blocks]]
type = 'prompt'
alignment = 'left'

  [[blocks.segments]]
  type = 'text'
  style = 'plain'
  template = "\u256d\u2500"
  foreground = '#f8f8f2'

    [blocks.segments.properties]
    cache_duration = 'none'

  [[blocks.segments]]
  type = 'root'  
  style = 'powerline'
  #template = "\udb85\udc0b"
  foreground = '#ff5555'
  powerline_symbol = "\ue0b0"
  
    [blocks.segments.properties]
    cache_duration = 'none'

  [[blocks.segments]]
  type = 'path'
  template = "{{ .Path  }}"
  style = 'diamond'
  leading_diamond = "\ue0b6"
  trailing_diamond = "\ue0b4"
  background = '#282a36'
  foreground = '#f8f8f2'

    [blocks.segments.properties]
    style = 'powerlevel'
    max_width = 25
    cache_duration = 'none'

  [[blocks.segments]]
#  background = '#2e9599'
#  background_templates = [ '{{ if or (.Working.Changed) (.Staging.Changed) }}#f36943{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#a8216b{{ end }}', '{{ if gt .Ahead 0 }}#35b5ff{{ end }}', '{{ if gt .Behind 0 }}#f89cfa{{ end }}' ]
  background = '#cccccc'
  foreground = '#282a36'
#  foreground = '#193549'
#  foreground_templates = [ '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ffffff{{ end }}' ]
  template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }} '
  style = 'diamond'
  trailing_diamond = ""
  type = 'git'

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_status = true
    cache_duration = 'none'

  [[blocks.segments]]
  type = 'status'
  style = 'diamond'
  background = '#e91e63'
  foreground = '#ffffff'
  template = "<parentBackground>  </>"
  trailing_diamond = ''

    [blocks.segments.properties]
    cache_duration = 'none'


#[[blocks]]
#alignment = 'right'
#overflow = 'hide'
#type = 'prompt'
#
#  [[blocks.segments]]
#  background = '#cccccc'
#  foreground = '#282a36'
#  template = '{{ .CurrentDate | date .Format }}'
#  style = 'diamond'
#  leading_diamond = "\ue0b6"
#  trailing_diamond = "\ue0b4"
#  type = 'time'


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

  [[blocks.segments]]
  type = 'text'
  style = 'diamond'
  template = "\u2570\u2500❯❯"
  foreground = '#f8f8f2'
  
    [blocks.segments.properties]
    always_enabled = true
    cache_duration = 'none'
