#!/bin/bash

sudo umount /dev/$1
sudo dd if=/dev/zero of=/dev/$1 bs=1M status=progress
sudo dd if=/dev/urandom of=/dev/$1 bs=1M status=progress
sudo mkfs.vfat -F 32 -n "$2" /dev/$1
sudo mkfs.ext4 /dev/$1
